#! /usr/bin/env bash
# https://medium.com/@zhelinchen91/how-to-convert-from-latex-to-ms-word-with-pandoc-f2045a762293
TEX=${1:-attila-nia-retreat-2021.tex}
DOCX=$(dirname $TEX)/$(basename $TEX .tex).docx
pandoc $TEX --bibliography=library.bib -o $DOCX
